# Generated by Django 5.1.6 on 2025-03-26 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_feedback_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={},
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='remaining_budget',
            new_name='remaining_amount',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='total_budget',
            new_name='total_amount',
        ),
        migrations.AlterField(
            model_name='budget',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
