# Generated by Django 5.1.6 on 2025-03-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='companion',
            name='age',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companion',
            name='name',
            field=models.CharField(default='Unnamed', max_length=100),
        ),
    ]
