# Generated by Django 5.1.6 on 2025-03-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_companion_age_companion_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companion',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
