# Generated by Django 5.1.6 on 2025-03-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_companion_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companion',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='companion',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='companion',
            name='relationship',
            field=models.CharField(max_length=255),
        ),
    ]
