# Generated by Django 5.1.6 on 2025-04-19 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_companion_age_alter_companion_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='pending', max_length=10),
        ),
    ]
